diary/urls.py
from django.urls import path
from .import views

app_name = 'diary'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'), #/diary
    path('add/', views.AddView.as_view(), name='add'), #/diary/add
    path('update/<int:pk>/', views.UpdateView.as_view(), name='update'),  # diary/update/1
    path('delete/<int:pk>/', views.DeleteView.as_view(), name='delete'),  # /diary/delete/1
    path('detail/<int:pk>/', views.DetailView.as_view(), name='detail'),  # /diary/detail/1
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('diary/', include('diary.urls')),
]

diary/models.py
from django.db import models
from django.utils import timezone  # djangoでは、datetime.now のかわりに、timezone.now で現在日付・時刻を取得する


class Day(models.Model):
    title = models.CharField('タイトル', max_length=200)
    text = models.TextField('本文')
    date = models.DateTimeField('日付', default=timezone.now)

    def __str__(self):
        return self.title

diary/forms.py
from django import forms
from .models import Day


class DayCreateForm(forms.ModelForm):

    class Meta:
        model = Day
        fields = '__all__'  # ('title', 'text', 'date')

diary/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import generic
from .forms import DayCreateForm
from .models import Day


class IndexView(generic.ListView):
    model = Day
    paginate_by = 3


class AddView(LoginRequiredMixin, generic.CreateView):
    model = Day
    form_class = DayCreateForm
    success_url = reverse_lazy('diary:index')


class UpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Day
    form_class = DayCreateForm
    success_url = reverse_lazy('diary:index')


class DeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Day
    success_url = reverse_lazy('diary:index')


class DetailView(generic.DetailView):
    model = Day

diary/templates/diary/base.html
<!doctype html>
<html lang="ja">
  <head>
    <title>日記アプリケーション</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
      <nav class="nav">
        <a class="nav-link" href="{% url 'diary:index' %}">一覧</a>
        {% if user.is_superuser %}
        <a class="nav-link" href="{% url 'admin:diary_day_add'%}" target="_blank">追加</a>
        {% endif%}
      </nav>
      {% block content %}
      {% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
  </body>
</html>

diary/templates/diary/day_confirm_delete.html
{% extends 'diary/base.html' %}

{% block content %}
<form action="" method="POST">
  <table class="table">
      <tr>
        <th>タイトル</th>
        <td>{{ day.title }}</td>
      </tr>
      <tr>
        <th>本文</th>
        <td>{{ day.text }}</td>
      </tr>
      <tr>
        <th>日付</th>
        <td>{{ day.date }}</td>
      </tr>
  </table>
  <p>こちらのデータを削除します。</p>
  <button type="submit" class="btn btn-primary">送信</button>
  {% csrf_token %}
</form>
{% endblock %}

diary/templates/diary/day_detail.html
{% extends 'diary/base.html' %}

{% block content %}
<table class="table">
    <tr>
      <th>タイトル</th>
      <td>{{ day.title }}</td>
    </tr>
    <tr>
      <th>本文</th>
      <td>{{ day.text | linebreaksbr}}</td>
    </tr>
    <tr>
      <th>日付</th>
      <td>{{ day.date }}</td>
    </tr>
</table>

{% endblock %}

diary/templates/diary/day_form.html
{% extends 'diary/base.html' %}

{% block content %}
<form action="" method="POST">
    {{ form.as_p }}
    <button type="submit">送信</button>
    {% csrf_token %}
</form>
{% endblock %}

diary/templates/diary/day_list.html
{% extends 'diary/base.html' %}

{% block content %}
<h1>日記一覧</h1>
<table class="table">
  <thead>
    <tr>
      <th>タイトル</th>
      <th>日付</th>
      <th>#</th>
      <th>#</th>
    </tr>
  </thead>
  <tbody>
    {% for day in day_list %}
    <tr>
      <td><a href="{% url 'diary:detail' day.pk %}">{{ day.title }}</a></td>
      <td>{{ day.date }}</td>
      <td>
        {% if user.is_superuser %}
          <a href="{% url 'admin:diary_day_change' day.pk %}" target="_blank">更新</a>
        {% endif %}
      </td>
      <td>
        {% if user.is_superuser %}
          <a href="{% url 'admin:diary_day_delete' day.pk %}" target="_blank">削除</a>
        {% endif %}
      </td>
    </tr>
  {% endfor %}
  </tbody>
</table>

{% include 'diary/page4.html' %}

{% endblock %}

diary/templates/diary/page1.html
<!-- 前へ の部分 -->
{% if page_obj.has_previous %}
  <a href="?page={{ page_obj.previous_page_number }}">前へ</a>
{% endif %}


<!-- 次へ の部分 -->
{% if page_obj.has_next %}
  <a href="?page={{ page_obj.next_page_number }}">次へ</a>
{% endif %}

diary/templates/diary/page2.html
<!-- 前へ の部分 -->
{% if page_obj.has_previous %}
  <a href="?page={{ page_obj.previous_page_number }}">前へ</a>
{% endif %}
 
<!-- 数字の部分 -->
{% for num in page_obj.paginator.page_range %}
  {% if page_obj.number == num %}
    <span>{{ num }}</span>
  {% else %}
    <a href="?page={{ num }}">{{ num }}</a>
  {% endif %}
{% endfor %}
 
<!-- 次へ の部分 -->
{% if page_obj.has_next %}
  <a href="?page={{ page_obj.next_page_number }}">次へ</a>
{% endif %}

diary/templates/diary/page3.html
<!-- 前へ の部分 -->
{% if page_obj.has_previous %}
  <a href="?page={{ page_obj.previous_page_number }}">前へ</a>
{% endif %}

<!-- 数字の部分 -->
Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
 
<!-- 次へ の部分 -->
{% if page_obj.has_next %}
  <a href="?page={{ page_obj.next_page_number }}">次へ</a>
{% endif %}

diary/templates/diary/page4.html
<nav aria-label="Page navigation">
  <ul class="pagination">
 
      {% if page_obj.has_previous %}
        <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      {% endif %}
    
      {% for link_page in page_obj.paginator.page_range %}
        {% if link_page == page_obj.number %}
          <li class="page-item active">
            <a class="page-link" href="?page={{ link_page }}">
              {{ link_page }}
            </a>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ link_page }}">
              {{ link_page }}
            </a>
          </li>
        {% endif %}
      {% endfor %}
    
      {% if page_obj.has_next %}
        <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
      {% endif %}
    
  </ul>
</nav>